# Pivot Data Analisys

In [16]:
import pandas as pd
import numpy as np

In [71]:
from dict import produtos, clientes, estados_cidades_bairros_lojas

In [81]:
dados = []
for estado, cidades in estados_cidades_bairros_lojas.items():
    for cidade, bairros in cidades.items():
        for bairro, lojas in bairros.items():
            for loja in lojas:
                for produto in produtos:
                    for cliente in clientes:
                        faturamento = int(np.random.randint(1, 20))  # 1000 a 20000
                        custo = int(faturamento * np.random.uniform(0.6, 0.8)) + 1  # 60% a 80% do faturamento
                        dados.append({
                            "Estado": estado,
                            "Cidade": cidade,
                            "Bairro": bairro,
                            "Loja": loja,
                            "Produto": produto,
                            "Cliente": cliente,
                            "Faturamento": faturamento,
                            "Custo": custo,
                        })

# Criando o DataFrame final
df = pd.DataFrame(dados)
df["Lucro"] = df["Faturamento"] - df["Custo"]
df

,Estado,Cidade,Bairro,Loja,Produto,Cliente,Faturamento,Custo,Lucro
0,SP,São Paulo,Vila Mariana,Bagre,Zorgonite,Doutor Niquete Socorrista,6,5,1
1,SP,São Paulo,Vila Mariana,Bagre,Zorgonite,Arquitetura Visconde Coração de Jesus,1,1,0
2,SP,São Paulo,Vila Mariana,Bagre,Zorgonite,Vitrola Tímpano Escola de Música Clássica,15,10,5
3,SP,São Paulo,Vila Mariana,Bagre,Zorgonite,Professor José de Sá Biologia Inteligente,18,14,4
4,SP,São Paulo,Vila Mariana,Bagre,Zorgonite,Rede Dura Associação de Detetives Confidenciais,19,14,5
...,...,...,...,...,...,...,...,...,...
16495,RS,Gramado,Bavária,Cachaça,Cristal Xyloriano,Arquitetura Visconde Coração de Jesus,18,12,6
16496,RS,Gramado,Bavária,Cachaça,Cristal Xyloriano,Vitrola Tímpano Escola de Música Clássica,16,12,4
16497,RS,Gramado,Bavária,Cachaça,Cristal Xyloriano,Professor José de Sá Biologia Inteligente,11,7,4
16498,RS,Gramado,Bavária,Cachaça,Cristal Xyloriano,Rede Dura Associação de Detetives Confidenciais,4,3,1
16499,RS,Gramado,Bavária,Cachaça,Cristal Xyloriano,Doutor Nado Meteorologista,15,11,4

In [88]:
# Qual é o faturamento total por produto em cada estado?
# Usando o método pivot para calcular o faturamento total por produto em cada estado
pivot_df = df.pivot_table(index="Estado", columns="Produto", values="Faturamento", aggfunc="sum", fill_value=0)

# Exibindo a tabela pivotada
pivot_df

Produto  Cristal Xyloriano  Nebulite  Plasma Ionizado  Quark Flux  Zorgonite
Estado
BA                    6009      6135             5862        5923       5969
MG                    4484      4611             4407        4290       4349
RJ                    7665      7610             7474        7717       7418
RS                    7623      7415             7389        7396       7635
SP                    7407      7551             7503        7540       7584

In [110]:
pivot_df = df.pivot_table(index="Estado", columns="Produto", values="Faturamento", aggfunc="sum", fill_value=0)
# Usando o método melt para voltar o DataFrame ao formato longo
melt_df = pivot_df.reset_index().melt(id_vars="Estado", var_name="Produto", value_name="Faturamento")

# Exibindo o DataFrame derretido (melted)
pivot_df = melt_df.pivot_table(index="Estado", columns="Produto", values="Faturamento", aggfunc="sum", fill_value=0)
# Usando o método melt para voltar o DataFrame ao formato longo
melt_df = pivot_df.reset_index().melt(id_vars="Estado", var_name="Produto", value_name="Faturamento")
pivot_df

Produto  Cristal Xyloriano  Nebulite  Plasma Ionizado  Quark Flux  Zorgonite
Estado
BA                    6009      6135             5862        5923       5969
MG                    4484      4611             4407        4290       4349
RJ                    7665      7610             7474        7717       7418
RS                    7623      7415             7389        7396       7635
SP                    7407      7551             7503        7540       7584

In [111]:
melt_df

   Estado            Produto  Faturamento
0      BA  Cristal Xyloriano         6009
1      MG  Cristal Xyloriano         4484
2      RJ  Cristal Xyloriano         7665
3      RS  Cristal Xyloriano         7623
4      SP  Cristal Xyloriano         7407
5      BA           Nebulite         6135
6      MG           Nebulite         4611
7      RJ           Nebulite         7610
8      RS           Nebulite         7415
9      SP           Nebulite         7551
10     BA    Plasma Ionizado         5862
11     MG    Plasma Ionizado         4407
12     RJ    Plasma Ionizado         7474
13     RS    Plasma Ionizado         7389
14     SP    Plasma Ionizado         7503
15     BA         Quark Flux         5923
16     MG         Quark Flux         4290
17     RJ         Quark Flux         7717
18     RS         Quark Flux         7396
19     SP         Quark Flux         7540
20     BA          Zorgonite         5969
21     MG          Zorgonite         4349
22     RJ          Zorgonite         7418
23     RS          Zorgonite         7635
24     SP          Zorgonite         7584

In [115]:
stacked_df = pivot_df.stack()
stacked_df

Estado  Produto
BA      Cristal Xyloriano    6009
        Nebulite             6135
        Plasma Ionizado      5862
        Quark Flux           5923
        Zorgonite            5969
MG      Cristal Xyloriano    4484
        Nebulite             4611
        Plasma Ionizado      4407
        Quark Flux           4290
        Zorgonite            4349
RJ      Cristal Xyloriano    7665
        Nebulite             7610
        Plasma Ionizado      7474
        Quark Flux           7717
        Zorgonite            7418
RS      Cristal Xyloriano    7623
        Nebulite             7415
        Plasma Ionizado      7389
        Quark Flux           7396
        Zorgonite            7635
SP      Cristal Xyloriano    7407
        Nebulite             7551
        Plasma Ionizado      7503
        Quark Flux           7540
        Zorgonite            7584
dtype: int64

In [122]:
# Aplicando unstack para mover o índice Produto para colunas
unstacked_df = stacked_df.unstack()
unstacked_df

Produto  Cristal Xyloriano  Nebulite  Plasma Ionizado  Quark Flux  Zorgonite
Estado
BA                    6009      6135             5862        5923       5969
MG                    4484      4611             4407        4290       4349
RJ                    7665      7610             7474        7717       7418
RS                    7623      7415             7389        7396       7635
SP                    7407      7551             7503        7540       7584

In [ ]:
# Criando um MultiIndex com Estado, Produto, e Loja
multiindex_df = df.set_index(["Estado", "Estado", "Bairro"])

# Exibindo o resultado
multiindex_df

                               Cidade     Loja            Produto  \
Estado Estado Bairro
SP     SP     Vila Mariana  São Paulo    Bagre          Zorgonite
              Vila Mariana  São Paulo    Bagre          Zorgonite
              Vila Mariana  São Paulo    Bagre          Zorgonite
              Vila Mariana  São Paulo    Bagre          Zorgonite
              Vila Mariana  São Paulo    Bagre          Zorgonite
...                               ...      ...                ...
RS     RS     Bavária         Gramado  Cachaça  Cristal Xyloriano
              Bavária         Gramado  Cachaça  Cristal Xyloriano
              Bavária         Gramado  Cachaça  Cristal Xyloriano
              Bavária         Gramado  Cachaça  Cristal Xyloriano
              Bavária         Gramado  Cachaça  Cristal Xyloriano

                                                                    Cliente  \
Estado Estado Bairro
SP     SP     Vila Mariana                        Doutor Niquete Socorrista
              Vila Mariana            Arquitetura Visconde Coração de Jesus
              Vila Mariana        Vitrola Tímpano Escola de Música Clássica
              Vila Mariana        Professor José de Sá Biologia Inteligente
              Vila Mariana  Rede Dura Associação de Detetives Confidenciais
...                                                                     ...
RS     RS     Bavária                 Arquitetura Visconde Coração de Jesus
              Bavária             Vitrola Tímpano Escola de Música Clássica
              Bavária             Professor José de Sá Biologia Inteligente
              Bavária       Rede Dura Associação de Detetives Confidenciais
              Bavária                            Doutor Nado Meteorologista

                            Faturamento  Custo  Lucro
Estado Estado Bairro
SP     SP     Vila Mariana            6      5      1
              Vila Mariana            1      1      0
              Vila Mariana           15     10      5
              Vila Mariana           18     14      4
              Vila Mariana           19     14      5
...                                 ...    ...    ...
RS     RS     Bavária                18     12      6
              Bavária                16     12      4
              Bavária                11      7      4
              Bavária                 4      3      1
              Bavária                15     11      4

[16500 rows x 7 columns]

### Sandart Intel

In [1]:
import sqlite3
import pandas as pd

In [28]:
# Caminho do banco de dados SQLite
db_path = r"D:\Fausto Stangler\Documentos\Python\FLY\backend\data\app_raw.db"

# Conectar ao banco de dados
conn = sqlite3.connect(db_path)

# Carregar os dados
df = pd.read_sql("SELECT * FROM tbl_statements_normalized", conn)  # Dados já processados

# Fechar a conexão com o banco de dados
conn.close()

df = df.loc[df.groupby(["company_name", "quarter", "type"])["version"].idxmax()]

In [23]:
df.columns

Index(['nsd', 'sector', 'subsector', 'segment', 'company_name', 'quarter',
       'version', 'type', 'frame', 'account', 'description', 'value',
       'original_value'],
      dtype='object')

In [27]:
mask = df["company_name"] == "ALPARGATAS SA"
mask &= df["account"] == "02"
mask &= df["type"] == "DFs Consolidadas"

df["account"].unique()

array(['01', '00.01.01', '02'], dtype=object)

In [ ]:
import sqlite3
import pandas as pd

# Caminho do banco de dados SQLite
db_path = r"D:\Fausto Stangler\Documentos\Python\FLY\backend\data\app_raw.db"

# Conectar ao banco de dados
conn = sqlite3.connect(db_path)

# Query SQL para carregar APENAS os dados que ainda não foram processados
query = """
SELECT 
FROM tbl_statements_raw
LEFT JOIN tbl_statements_normalized
ON tbl_statements_raw.company_name = tbl_statements_normalized.company_name
AND tbl_statements_raw.quarter = prtbl_statements_normalizedocessed.quarter
AND tbl_statements_raw.type = proctbl_statements_normalizedessed.type
AND tbl_statements_raw.frame = tbl_statements_normalized.frame
WHERE tbl_statements_normalized.company_name IS NULL;
"""

# Executar a query no banco de dados e carregar no pandas
df = pd.read_sql(query, conn)

# Fechar a conexão com o banco de dados
conn.close()

# Agora `financial_statements` contém apenas os registros que ainda NÃO foram processados
df

,nsd,sector,subsector,segment,company_name,quarter,version,type,frame,account,description,value
0,6161,BENS INDUSTRIAIS,MAQUINAS E EQUIPAMENTOS,MAQ E EQUIP INDUSTRIAIS,INEPAR SA INDUSTRIA E CONSTRUCOES,2010-12-31T00:00:00,1,Dados da Empresa,Composição do Capital,00.01.01,Ações ON Ordinárias,37165000.0
1,6610,BENS INDUSTRIAIS,MAQUINAS E EQUIPAMENTOS,MAQ E EQUIP INDUSTRIAIS,INEPAR SA INDUSTRIA E CONSTRUCOES,2010-12-31T00:00:00,2,Dados da Empresa,Composição do Capital,00.01.01,Ações ON Ordinárias,37165000.0
2,6838,BENS INDUSTRIAIS,MAQUINAS E EQUIPAMENTOS,MAQ E EQUIP INDUSTRIAIS,INEPAR SA INDUSTRIA E CONSTRUCOES,2010-12-31T00:00:00,3,Dados da Empresa,Composição do Capital,00.01.01,Ações ON Ordinárias,37165000.0
3,6161,BENS INDUSTRIAIS,MAQUINAS E EQUIPAMENTOS,MAQ E EQUIP INDUSTRIAIS,INEPAR SA INDUSTRIA E CONSTRUCOES,2010-12-31T00:00:00,1,Dados da Empresa,Composição do Capital,00.01.02,Ações PN Preferenciais,58495000.0
4,6610,BENS INDUSTRIAIS,MAQUINAS E EQUIPAMENTOS,MAQ E EQUIP INDUSTRIAIS,INEPAR SA INDUSTRIA E CONSTRUCOES,2010-12-31T00:00:00,2,Dados da Empresa,Composição do Capital,00.01.02,Ações PN Preferenciais,58495000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9093798,137117,None,None,None,BRAZIL TOWER CESSAO DE INFRAESTRUTURAS SA,2024-03-31T00:00:00,1,DFs Individuais,Demonstração de Valor Adicionado,7.08.05,Outros,0.0
9093799,137117,None,None,None,BRAZIL TOWER CESSAO DE INFRAESTRUTURAS SA,2024-03-31T00:00:00,1,Dados da Empresa,Composição do Capital,00.01.01,Ações ON Ordinárias,108417531.0
9093800,137117,None,None,None,BRAZIL TOWER CESSAO DE INFRAESTRUTURAS SA,2024-03-31T00:00:00,1,Dados da Empresa,Composição do Capital,00.01.02,Ações PN Preferenciais,0.0
9093801,137117,None,None,None,BRAZIL TOWER CESSAO DE INFRAESTRUTURAS SA,2024-03-31T00:00:00,1,Dados da Empresa,Composição do Capital,00.02.01,Em Tesouraria Ações ON Ordinárias,0.0
9093802,137117,None,None,None,BRAZIL TOWER CESSAO DE INFRAESTRUTURAS SA,2024-03-31T00:00:00,1,Dados da Empresa,Composição do Capital,00.02.02,Em Tesouraria Ações PN Preferenciais,0.0

In [26]:
df

,nsd,sector,subsector,segment,company_name,quarter,version,type,frame,account,description,value
0,6161,BENS INDUSTRIAIS,MAQUINAS E EQUIPAMENTOS,MAQ E EQUIP INDUSTRIAIS,INEPAR SA INDUSTRIA E CONSTRUCOES,2010-12-31T00:00:00,1,Dados da Empresa,Composição do Capital,00.01.01,Ações ON Ordinárias,37165000.0
1,6610,BENS INDUSTRIAIS,MAQUINAS E EQUIPAMENTOS,MAQ E EQUIP INDUSTRIAIS,INEPAR SA INDUSTRIA E CONSTRUCOES,2010-12-31T00:00:00,2,Dados da Empresa,Composição do Capital,00.01.01,Ações ON Ordinárias,37165000.0
2,6838,BENS INDUSTRIAIS,MAQUINAS E EQUIPAMENTOS,MAQ E EQUIP INDUSTRIAIS,INEPAR SA INDUSTRIA E CONSTRUCOES,2010-12-31T00:00:00,3,Dados da Empresa,Composição do Capital,00.01.01,Ações ON Ordinárias,37165000.0
3,6161,BENS INDUSTRIAIS,MAQUINAS E EQUIPAMENTOS,MAQ E EQUIP INDUSTRIAIS,INEPAR SA INDUSTRIA E CONSTRUCOES,2010-12-31T00:00:00,1,Dados da Empresa,Composição do Capital,00.01.02,Ações PN Preferenciais,58495000.0
4,6610,BENS INDUSTRIAIS,MAQUINAS E EQUIPAMENTOS,MAQ E EQUIP INDUSTRIAIS,INEPAR SA INDUSTRIA E CONSTRUCOES,2010-12-31T00:00:00,2,Dados da Empresa,Composição do Capital,00.01.02,Ações PN Preferenciais,58495000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9093798,137117,None,None,None,BRAZIL TOWER CESSAO DE INFRAESTRUTURAS SA,2024-03-31T00:00:00,1,DFs Individuais,Demonstração de Valor Adicionado,7.08.05,Outros,0.0
9093799,137117,None,None,None,BRAZIL TOWER CESSAO DE INFRAESTRUTURAS SA,2024-03-31T00:00:00,1,Dados da Empresa,Composição do Capital,00.01.01,Ações ON Ordinárias,108417531.0
9093800,137117,None,None,None,BRAZIL TOWER CESSAO DE INFRAESTRUTURAS SA,2024-03-31T00:00:00,1,Dados da Empresa,Composição do Capital,00.01.02,Ações PN Preferenciais,0.0
9093801,137117,None,None,None,BRAZIL TOWER CESSAO DE INFRAESTRUTURAS SA,2024-03-31T00:00:00,1,Dados da Empresa,Composição do Capital,00.02.01,Em Tesouraria Ações ON Ordinárias,0.0
9093802,137117,None,None,None,BRAZIL TOWER CESSAO DE INFRAESTRUTURAS SA,2024-03-31T00:00:00,1,Dados da Empresa,Composição do Capital,00.02.02,Em Tesouraria Ações PN Preferenciais,0.0

In [20]:
financial_statements = pd.read_csv("financial_statements.csv")
standart_statements = pd.read_csv("standart_statements.csv")
primary_key_columns = ["company_name", "quarter", "version", "type", "frame"]

In [24]:
financial_statements

,nsd,sector,subsector,segment,company_name,quarter,version,type,frame,account,description,value
0,58916,BENS INDUSTRIAIS,COMERCIO,MATERIAL DE TRANSPORTE,MINASMAQUINAS SA,2016-06-30T00:00:00,1,Dados da Empresa,Composição do Capital,00.01.01,Ações ON Ordinárias,2.200000e+04
1,58916,BENS INDUSTRIAIS,COMERCIO,MATERIAL DE TRANSPORTE,MINASMAQUINAS SA,2016-06-30T00:00:00,1,Dados da Empresa,Composição do Capital,00.01.02,Ações PN Preferenciais,2.200000e+04
2,58916,BENS INDUSTRIAIS,COMERCIO,MATERIAL DE TRANSPORTE,MINASMAQUINAS SA,2016-06-30T00:00:00,1,Dados da Empresa,Composição do Capital,00.02.01,Em Tesouraria Ações ON Ordinárias,1.000000e+03
3,58916,BENS INDUSTRIAIS,COMERCIO,MATERIAL DE TRANSPORTE,MINASMAQUINAS SA,2016-06-30T00:00:00,1,Dados da Empresa,Composição do Capital,00.02.02,Em Tesouraria Ações PN Preferenciais,2.000000e+03
4,58916,BENS INDUSTRIAIS,COMERCIO,MATERIAL DE TRANSPORTE,MINASMAQUINAS SA,2016-06-30T00:00:00,1,DFs Individuais,Balanço Patrimonial Ativo,1,Ativo Total,1.370990e+09
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,12704,BENS INDUSTRIAIS,TRANSPORTE,TRANSPORTE FERROVIARIO,RUMO MALHA PAULISTA SA,2011-09-30T00:00:00,1,DFs Individuais,Balanço Patrimonial Ativo,1.01.02.01.01,Títulos para Negociação,0.000000e+00
999996,12704,BENS INDUSTRIAIS,TRANSPORTE,TRANSPORTE FERROVIARIO,RUMO MALHA PAULISTA SA,2011-09-30T00:00:00,1,DFs Consolidadas,Balanço Patrimonial Ativo,1.01.02.01.02,Títulos Disponíveis para Venda,0.000000e+00
999997,12704,BENS INDUSTRIAIS,TRANSPORTE,TRANSPORTE FERROVIARIO,RUMO MALHA PAULISTA SA,2011-09-30T00:00:00,1,DFs Individuais,Balanço Patrimonial Ativo,1.01.02.01.02,Títulos Disponíveis para Venda,0.000000e+00
999998,12704,BENS INDUSTRIAIS,TRANSPORTE,TRANSPORTE FERROVIARIO,RUMO MALHA PAULISTA SA,2011-09-30T00:00:00,1,DFs Consolidadas,Balanço Patrimonial Ativo,1.01.02.02,Aplicações Financeiras Avaliadas ao Custo Amor...,0.000000e+00
999999,12704,BENS INDUSTRIAIS,TRANSPORTE,TRANSPORTE FERROVIARIO,RUMO MALHA PAULISTA SA,2011-09-30T00:00:00,1,DFs Individuais,Balanço Patrimonial Ativo,1.01.02.02,Aplicações Financeiras Avaliadas ao Custo Amor...,0.000000e+00

In [ ]:
df = pd.merge(
    standart_statements, financial_statements[primary_key_columns], on=primary_key_columns, how="left", indicator=True
)
df

,nsd,sector,subsector,segment,company_name,quarter,version,type,frame,account,description,value,_merge
0,58916,BENS INDUSTRIAIS,COMERCIO,MATERIAL DE TRANSPORTE,MINASMAQUINAS SA,2016-06-30T00:00:00,1,Dados da Empresa,Composição do Capital,00.01.01,Ações ON Ordinárias,22000.0,both
1,58916,BENS INDUSTRIAIS,COMERCIO,MATERIAL DE TRANSPORTE,MINASMAQUINAS SA,2016-06-30T00:00:00,1,Dados da Empresa,Composição do Capital,00.01.01,Ações ON Ordinárias,22000.0,both
2,58916,BENS INDUSTRIAIS,COMERCIO,MATERIAL DE TRANSPORTE,MINASMAQUINAS SA,2016-06-30T00:00:00,1,Dados da Empresa,Composição do Capital,00.01.01,Ações ON Ordinárias,22000.0,both
3,58916,BENS INDUSTRIAIS,COMERCIO,MATERIAL DE TRANSPORTE,MINASMAQUINAS SA,2016-06-30T00:00:00,1,Dados da Empresa,Composição do Capital,00.01.01,Ações ON Ordinárias,22000.0,both
4,58916,BENS INDUSTRIAIS,COMERCIO,MATERIAL DE TRANSPORTE,MINASMAQUINAS SA,2016-06-30T00:00:00,1,Dados da Empresa,Composição do Capital,00.01.02,Ações PN Preferenciais,22000.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...
365300,98305,BENS INDUSTRIAIS,COMERCIO,MATERIAL DE TRANSPORTE,MINASMAQUINAS SA,2020-09-30T00:00:00,1,DFs Individuais,Demonstração de Valor Adicionado,07.08.05.09,Outros,0.0,both
365301,98305,BENS INDUSTRIAIS,COMERCIO,MATERIAL DE TRANSPORTE,MINASMAQUINAS SA,2020-09-30T00:00:00,1,DFs Individuais,Demonstração de Valor Adicionado,07.08.05.09,Outros,0.0,both
365302,98305,BENS INDUSTRIAIS,COMERCIO,MATERIAL DE TRANSPORTE,MINASMAQUINAS SA,2020-09-30T00:00:00,1,DFs Individuais,Demonstração de Valor Adicionado,07.08.05.09,Outros,0.0,both
365303,98305,BENS INDUSTRIAIS,COMERCIO,MATERIAL DE TRANSPORTE,MINASMAQUINAS SA,2020-09-30T00:00:00,1,DFs Individuais,Demonstração de Valor Adicionado,07.08.05.09,Outros,0.0,both
365304,98305,BENS INDUSTRIAIS,COMERCIO,MATERIAL DE TRANSPORTE,MINASMAQUINAS SA,2020-09-30T00:00:00,1,DFs Individuais,Demonstração de Valor Adicionado,07.08.05.09,Outros,0.0,both

# Playground

In [7]:
import pandas as pd
import os
import sqlite3
import sys

# Add the backend folder to the Python path
backend_dir = os.path.join(os.getcwd(), "backend")
if backend_dir not in sys.path:
    sys.path.append(backend_dir)

In [ ]:
corporate_events = self.load_data(
    table_name=self.config.corporate_events_data_table, db_filepath=self.config.metadados_filepath
)
historical_data = self.load_data(table_name=self.config.historical_data, db_filepath=self.config.metadados_filepath)

### Play

In [8]:
# imports
from utils.corporate_events_processor import CorporateEventsProcessor

self = CorporateEventsProcessor()

In [404]:
# define dataframe variables

company_info_table = self.config.company_table  # from Database metadados
historical_data_table = self.config.historical_data  # from Database metadados
corporate_events_table = self.config.corporate_events_data_table  # from Database metadados
table_name_statements = self.config.statements_file  # from Database statements

db_filepath_metadados = self.config.metadados_filepath  # Database metadados path
db_filepath_statements = self.config.initial_filepath  # Database statements path
db_filepath_statements = (
    r"D:\Fausto Stangler\Documentos\Python\FLY\backend\data\statements initial - Copy.db"  # debugging
)

In [405]:
# def explode_company(self, all_company_info):
#     '''
#     '''
#     try:
#         # Ensure lists in `ticker_codes` and `isin_codes` are properly parsed
#         all_company_info['ticker_codes'] = all_company_info['ticker_codes'].apply(lambda x: ast.literal_eval(x) if pd.notna(x) else [])
#         all_company_info['isin_codes'] = all_company_info['isin_codes'].apply(lambda x: ast.literal_eval(x) if pd.notna(x) else [])

#         # Step 1: Add `ticker_isin` column to `company_info`
#         all_company_info['ticker_isin'] = all_company_info.apply(
#             lambda row: [(ticker, isin) for ticker, isin in zip(row['ticker_codes'], row['isin_codes']) if 'ACN' in isin],
#             axis=1
#         )

#         return all_company_info
#     except Exception as e:
#         self.log_error(e)

In [413]:
# def load_historical_data(self, data, ticker, tick, er, isin):
#     '''
#     '''
#     try:
#         # load historical_data['ticker']
#         # SQL query
#         query_historical_data = f"""
#         SELECT *
#         FROM {self.config.historical_data_table}
#         WHERE ticker = ?
#         """

#         # Load corporate_events['isin']
#         # SQL query
#         query_corporate_events = f"""
#         SELECT *
#         FROM {corporate_events_table}
#         WHERE ticker = ? AND (isin_code = ? OR isin_code = ?)
#         """

#         # Load data into a Pandas DataFrame
#         with sqlite3.connect(db_filepath_metadados) as conn:
#             data[ticker]['historical_data'] = pd.read_sql_query(query_historical_data, conn, params=(ticker,))
#             data[ticker]['corporate_events'] = pd.read_sql_query(query_corporate_events, conn, params=(tick, er, isin,))

#         # Convert date columns to datetime for proper alignment
#         data[ticker]['historical_data']['date'] = pd.to_datetime(data[ticker]['historical_data']['date'])
#         data[ticker]['corporate_events']['ex_date'] = pd.to_datetime(data[ticker]['corporate_events']['ex_date'])

#         # sorting
#         data[ticker]['historical_data'] = data[ticker]['historical_data'].sort_values(by='date')
#         data[ticker]['corporate_events'] = data[ticker]['corporate_events'].sort_values(by='ex_date')

#     except Exception as e:
#         self.log_error(e)

#     return data

In [407]:
# def load_statements_data(self, data, ticker, company_name):
#     '''
#     '''
#     try:
#         # load statements['company_name'] BCO BRASIL SA & description contains ON, da isin do company_info, and types
#         types = 'Dados da Empresa'

#         query = f"""
#         SELECT *
#         FROM {table_name_statements}
#         WHERE company_name = ? AND type = ?
#         """

#         # Execute the query
#         with sqlite3.connect(db_filepath_statements) as conn:
#             data[ticker]['statements'] = pd.read_sql_query(query, conn, params=(company_name, types))

#         data[ticker]['statements']['quarter'] = pd.to_datetime(data[ticker]['statements']['quarter'])

#         data[ticker]['statements'] = data[ticker]['statements'].pivot_table(
#             index=['nsd', 'sector', 'subsector', 'segment', 'company_name', 'quarter', 'version', 'type', 'frame'],
#             columns=['account', 'description'],
#             values='value',
#             aggfunc='first'  # Use the first value in case of duplicates
#         ).reset_index()

#         # Flatten the multi-level columns
#         joiner = ' - '
#         data[ticker]['statements'].columns = [joiner.join(col).rstrip(joiner) for col in data[ticker]['statements'].columns]
#         data[ticker]['statements']['00.03 - Ações ON'] = data[ticker]['statements']['00.01.01 - Ações ON Ordinárias'] + data[ticker]['statements']['00.02.01 - Em Tesouraria Ações ON Ordinárias']
#         data[ticker]['statements']['00.04 - Ações PN'] = data[ticker]['statements']['00.01.02 - Ações PN Preferenciais'] + data[ticker]['statements']['00.02.02 - Em Tesouraria Ações PN Preferenciais']

#         # Sort the DataFrame by quarter and version in ascending order
#         data[ticker]['statements'] = data[ticker]['statements'].sort_values(by=['quarter', 'version'], ascending=[True, False])

#         # Drop duplicates, keeping the first occurrence (highest version)
#         data[ticker]['statements'] = data[ticker]['statements'].drop_duplicates(subset=['quarter', 'sector', 'subsector', 'segment', 'company_name', 'type', 'frame'], keep='first')

#         data[ticker]['statements']['start_quarter_date'] = data[ticker]['statements']['quarter'] - pd.offsets.QuarterBegin(startingMonth=1)

#     except Exception as e:
#         self.log_error(e)

#     return data

In [408]:
# def mutual_maping(self, data, ticker):
#     '''
#     '''
#     try:
#         company_info = data[ticker]['company_info']
#         historical_data = data[ticker]['historical_data']
#         corporate_events = data[ticker]['corporate_events']
#         statements_data = data[ticker]['statements']

#         # mutual mapping

#         #  Map `isin_code` in `corporate_events` to `ticker` using `ticker_isin`
#         ticker_isin_mapping = {}
#         for _, row in company_info.iterrows():
#             for ticker, isin in row['ticker_isin']:
#                 ticker_isin_mapping[isin] = ticker
#         corporate_events['ticker_from_isin'] = corporate_events['isin_code'].map(ticker_isin_mapping)


#         statements_data = statements_data.merge(
#             company_info[['company_name', 'cvm_code', 'ticker']],  # Only keep the necessary columns
#             on=['company_name'],
#             how='left'
#         )


#         # Map historical_data['ticker'] to company_info_expanded['ticker_codes']
#         historical_data = historical_data.merge(
#             company_info.explode('ticker_codes')[['ticker_codes', 'company_name']],
#             left_on='ticker',
#             right_on='ticker_codes',
#             how='left'
#         )


#         data[ticker]['company_info'] = company_info
#         data[ticker]['historical_data'] = historical_data
#         data[ticker]['corporate_events'] = corporate_events
#         data[ticker]['statements_data'] = statements_data

#     except Exception as e:
#         self.log_error(e)

#     return data

In [409]:
def apply_corporate_events(self, data, ticker):
    """ """
    try:
        company_info = data[ticker]["company_info"]
        historical_data = data[ticker]["historical_data"]
        corporate_events = data[ticker]["corporate_events"]
        statements_data = data[ticker]["statements"]

        # filter corporate_events
        mask = corporate_events["source"].isin(["assets", "subscription"])
        mask &= corporate_events["ex_date"] >= statements_data["quarter"].min()
        corporate_events_filtered = corporate_events[mask]

        stock_columns = [col for col in statements_data.columns if self.config.joint in col]

        # Perform the asof merge by company_name and align nearest quarter <= date
        historical_statements_data = pd.merge_asof(
            historical_data[["date", "company_name"]],
            statements_data,
            by="company_name",
            left_on="date",
            right_on="quarter",
            direction="backward",  # Get the most recent financial data up to the historical date
        )

        changes = {}
        for _, event in corporate_events_filtered.iterrows():
            changes[ticker] = {}
            ticker = event["ticker_from_isin"]
            event_date = event["ex_date"]
            factor = event["price_or_factor"]
            action = event["corporate_action"]

            # Determine stock type columns based on ticker suffix
            if ticker.endswith("3"):
                affected_columns = [col for col in historical_statements_data.columns if "ON" in col]
            else:
                affected_columns = [col for col in historical_statements_data.columns if "PN" in col]

            if action == "DESDOBRAMENTO":
                calculated_factor = (
                    (100 + factor) / 100
                )  # 100 aumenta de 100 e vira 200, ou seja, multiplica por 2; 400 aumenta de 100 e vira 500, ou seja, multiplica por 5
            if action == "GRUPAMENTO":
                calculated_factor = factor  # 0,01 divide por 100, ou seja, 100 vira 1
            if action == "BONIFICACAO":
                calculated_factor = (100 + factor) / 100  # 30 signifca aumento de 30%, ou seja, 100 vira 130

            changes[ticker]["action"] = action
            changes[ticker]["event_date"] = event_date
            changes[ticker]["factor"] = factor
            changes[ticker]["calculated_factor"] = calculated_factor
            changes[ticker]["affected_columns"] = affected_columns

            # Apply factor to rows where the date is greater than the event date
            mask = historical_statements_data["date"] > event_date
            changes[ticker]["com value"] = historical_statements_data.loc[mask, affected_columns].iloc[0]
            historical_statements_data.loc[mask, affected_columns] *= calculated_factor
            changes[ticker]["ex value"] = historical_statements_data.loc[mask, affected_columns].iloc[0]

        data[ticker]["company_info"] = company_info
        data[ticker]["historical_data"] = historical_data
        data[ticker]["corporate_events"] = corporate_events
        data[ticker]["statements_data"] = statements_data
        data[ticker]["historical_statements_data"] = historical_statements_data
        data[ticker]["changes"] = changes

    except Exception as e:
        self.log_error(e)

    return data

In [410]:
# def prepare_data(self, ticker_isin, company_info_df):
#     '''
#     '''
#     data = {}
#     try:
#         for ticker, isin in ticker_isin:
#             data[ticker] = {}
#             data[ticker]['company_info'] = company_info_df

#             tick = ticker[:4]
#             er = ticker[4:]
#             er = self.config.tipos_acoes[er].split('(')[-1].strip(')')

#             data = load_historical_data(self, data, ticker, tick, er, isin)

#             data = load_statements_data(self, data, ticker, tick, er, isin)

#             data = mutual_maping(self, data, ticker)

#             data = apply_corporate_events(self, data, ticker)

#     except Exception as e:
#         self.log_error(e)

#     return data

In [411]:
# # load company data and prepare it
# # carregar a company_info
# all_company_info = self.load_data(table_name=company_info_table, db_filepath=db_filepath_metadados)

# all_company_info = explode_company(self, all_company_info)

  100.00% (1+0), 0.0040s per item, 0h 00m 00s = 0h 00m 00s + 0h 00m 00s Parte 1/1 metadados.db company_info

In [414]:
try:
    # for company in company_df
    for i, row in all_company_info.iterrows():
        cvm_code = row["cvm_code"]
        company_name = row["company_name"]
        ticker_isin = row["ticker_isin"]
        company_info_df = pd.DataFrame(row).T

        data = prepare_data(self, ticker_isin, company_info_df)
except Exception as e:
    self.log_error(e)

# save data
# to implement

Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given
Error in load_historical_data (line 35): 'Config' object has no attribute 'historical_data_table'
Error in prepare_data (line 23): load_statements_data() takes 4 positional arguments but 6 were given

### Stock Splits with YFinance

In [2]:
# mesclar as cotações históricas do yfinance, com as stocks dos statements ajustadas pela data exata (e não trimestral) do split pelo yfinance.

# para cada stock_ticker (BBAS3, etc), scrape historical_data do yahoo finance (já ajustado)

# para cada stock_ticker, pegar o calendário de splits (similar acima, mas somente as datas (que são iguais) e os splits)

# fazer um merge do statements por trimestre com o stock_splits por dia e ajustar a quantidade de ações quando houver split. A questão é saber quando a quantidade precisa ser ajustasa e quando la já está ajustada.
# Eu sei que no começo de cada trimestre a quantidade de stocks já está corrigida, e no começo do trimestre anterior ela está antiga. Em algum momento houve a mudança, e a data exata está
# no stock_split. Então quando o stock_split tiver uma informação, para aquele quarter eu preciso deixar o valor como está desta data-ex do stock_split para antes, e ajustar a quantidade de ações
# (dependendo se é grupamento ou desdobramento) para a quantidade de ações do statements desta data em diante. REpetindo, da data_ex (via stock_splits) para antes, copiar o valor diário do
# statements (que está trimestral) e da data-ex para diante, ajustar a quantidade de stocks do statements conforme o valor do split no stock_splits, e deixar como valor diário)

# Usar o BBAS3 como exemplo para 2024 quando houve stock_split

# então tem que abrir cxompany_info, iterar até bbas3, e então abrir statements do bbas3 e download historical_data e stock_splits do yfinance. Esses dados do yfinance podem ser salvos
# no metadados db, mas vão estar sempre defasados. Então na verdade, tem que abrir do historical_data e stock_splits, fazer um update com start_date só mais recente, limpar os dados
# proceder com o merge, e então atualizar o metadados db.

# e então calcular por exemplo, o preço por ação (porque a quantiade de ações vai estar certa a cada dia)

In [26]:
import yfinance as yf
import numpy as np
import pandas as pd
import os
import sys

In [27]:
# imports
# Add the backend folder to the Python path
backend_dir = os.path.join(os.getcwd(), "backend")
if backend_dir not in sys.path:
    sys.path.append(backend_dir)
from utils.corporate_events_processor import CorporateEventsProcessor

self = CorporateEventsProcessor()

In [20]:
# get yfinance data and yfinance splits
company_name = "BCO BRASIL SA"
ticker = ticker_code = "BBAS3"
start_date = "1960-01-01"


historical_splits = yf.download(
    ticker + ".SA", start=start_date, progress=False, actions=True, auto_adjust=True
).reset_index()
historical_splits.columns = historical_splits.columns.get_level_values(0).rename(None)
historical_splits = historical_splits[["Date", "Dividends", "Stock Splits"]]
historical_splits = historical_splits.loc[
    ~((historical_splits["Dividends"] == 0) & (historical_splits["Stock Splits"] == 0))
]
historical_splits.replace(0, np.nan, inplace=True)

historical_data = yf.download(
    ticker + ".SA", start=start_date, progress=False, actions=True, auto_adjust=True
).reset_index()
# historical_data.columns = historical_data.columns.get_level_values(0).rename(None)

In [29]:
ticker_obj = yf.Ticker(ticker_code + ".SA")
historical_data = ticker_obj.history(start=start_date, actions=True, auto_adjust=True).reset_index()
historical_data.columns = historical_data.columns.str.lower().str.replace(" ", "_")
historical_data["date"] = pd.to_datetime(historical_data["date"]).dt.strftime("%Y-%m-%d")
historical_data["company_name"] = company_name
historical_data["ticker"] = ticker
historical_data["ticker_code"] = ticker_code
historical_data = historical_data[self.config.historical_stock_data_all_columns]

In [40]:
mask = historical_data["stock_splits"] != 0
historical_data[mask][["date", "stock_splits"]]

            date  stock_splits
1915  2007-06-04           3.0
6098  2024-04-16           2.0

In [14]:
historical_data.columns

MultiIndex([(        'Date',         ''),
            (       'Close', 'BBAS3.SA'),
            (   'Dividends', 'BBAS3.SA'),
            (        'High', 'BBAS3.SA'),
            (         'Low', 'BBAS3.SA'),
            (        'Open', 'BBAS3.SA'),
            ('Stock Splits', 'BBAS3.SA'),
            (      'Volume', 'BBAS3.SA')],
           names=['Price', 'Ticker'])

In [10]:
historical_data

,Date,Close,Dividends,High,Low,Open,Stock Splits,Volume
0,2000-01-03,0.485271,0.0,0.506576,0.485271,0.497107,0.0,1029600
1,2000-01-04,0.462191,0.0,0.486455,0.462191,0.485271,0.0,628200
2,2000-01-05,0.466926,0.0,0.467518,0.445029,0.461600,0.0,957600
3,2000-01-06,0.473436,0.0,0.473436,0.461600,0.466926,0.0,410400
4,2000-01-07,0.462783,0.0,0.473435,0.462783,0.473435,0.0,788400
...,...,...,...,...,...,...,...,...
6284,2025-01-13,24.209999,0.0,24.430000,24.160000,24.209999,0.0,9941700
6285,2025-01-14,24.650000,0.0,24.670000,24.170000,24.250000,0.0,18049200
6286,2025-01-15,25.270000,0.0,25.370001,24.750000,24.910000,0.0,19626500
6287,2025-01-16,25.379999,0.0,25.459999,25.110001,25.280001,0.0,13590200
6288,2025-01-17,25.350000,0.0,25.490000,25.190001,25.440001,0.0,13271300

In [25]:
historical_data

,Date,Adj Close,Close,Dividends,High,Low,Open,Stock Splits,Volume
0,2000-01-03,0.485294,1.366666,0.0,1.426666,1.366666,1.400000,0.0,1029600
1,2000-01-04,0.462212,1.301666,0.0,1.370000,1.301666,1.366666,0.0,628200
2,2000-01-05,0.466947,1.315000,0.0,1.316666,1.253333,1.300000,0.0,957600
3,2000-01-06,0.473457,1.333333,0.0,1.333333,1.300000,1.315000,0.0,410400
4,2000-01-07,0.462804,1.303333,0.0,1.333333,1.303333,1.333333,0.0,788400
...,...,...,...,...,...,...,...,...,...
6284,2025-01-13,24.209999,24.209999,0.0,24.430000,24.160000,24.209999,0.0,9941700
6285,2025-01-14,24.650000,24.650000,0.0,24.670000,24.170000,24.250000,0.0,18049200
6286,2025-01-15,25.270000,25.270000,0.0,25.370001,24.750000,24.910000,0.0,19626500
6287,2025-01-16,25.379999,25.379999,0.0,25.459999,25.110001,25.280001,0.0,13590200
6288,2025-01-17,25.350000,25.350000,0.0,25.490000,25.190001,25.440001,0.0,13271300

In [20]:
historical_data

,Date,Adj Close,Close,High,Low,Open,Volume
0,2000-01-03,0.485293,1.366666,1.426666,1.366666,1.400000,1029600
1,2000-01-04,0.462212,1.301666,1.370000,1.301666,1.366666,628200
2,2000-01-05,0.466947,1.315000,1.316666,1.253333,1.300000,957600
3,2000-01-06,0.473457,1.333333,1.333333,1.300000,1.315000,410400
4,2000-01-07,0.462804,1.303333,1.333333,1.303333,1.333333,788400
...,...,...,...,...,...,...,...
6284,2025-01-13,24.209999,24.209999,24.430000,24.160000,24.209999,9941700
6285,2025-01-14,24.650000,24.650000,24.670000,24.170000,24.250000,18049200
6286,2025-01-15,25.270000,25.270000,25.370001,24.750000,24.910000,19626500
6287,2025-01-16,25.379999,25.379999,25.459999,25.110001,25.280001,13590200
6288,2025-01-17,25.350000,25.350000,25.490000,25.190001,25.440001,13271300

In [12]:
historical_splits

           Date  Dividends  Stock Splits
1915 2007-06-04        NaN           3.0
2421 2009-06-23   0.090111           NaN
2459 2009-08-14   0.095437           NaN
2485 2009-09-22   0.092699           NaN
2521 2009-11-13   0.061449           NaN
...         ...        ...           ...
6139 2024-06-14   0.204240           NaN
6188 2024-08-22   0.473352           NaN
6203 2024-09-12   0.186602           NaN
6254 2024-11-26   0.483304           NaN
6266 2024-12-12   0.176491           NaN

[124 rows x 3 columns]

In [584]:
historical_splits[historical_splits["Stock Splits"].notnull()][["Date", "Stock Splits"]]

           Date  Stock Splits
1915 2007-06-04           3.0
6098 2024-04-16           2.0

In [ ]:
# from statements, get stock_quantity and put it from quarters to daily basis

# merge statements_stock_quantity with daily_splits to apply changes to stock quantity

# from yfinance data merge by date to stock_quantity_adjusted to get stock_value_and_quantity

In [131]:
ticker = "AFYA5"
historical_splits = yf.download(
    ticker + ".SA", start=start_date, progress=False, actions=True, auto_adjust=True
).reset_index()
historical_splits

1 Failed download:
['AFYA5.SA']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

Empty DataFrame
Columns: [(Date, ), (Adj Close, AFYA5.SA), (Close, AFYA5.SA), (High, AFYA5.SA), (Low, AFYA5.SA), (Open, AFYA5.SA), (Volume, AFYA5.SA)]
Index: []

### Historical Data yFinance

In [528]:
ticker = "BBAS3"
ticker_code = ticker + ".SA"
start_date = "1960-01-01"


data = yf.download(ticker_code, start=start_date, progress=False, actions=True, auto_adjust=True).reset_index()

In [529]:
data

,Date,Close,Dividends,High,Low,Open,Stock Splits,Volume
0,2000-01-03,0.485503,0.0,0.506818,0.485503,0.497345,0.0,1029600
1,2000-01-04,0.462412,0.0,0.486688,0.462412,0.485503,0.0,628200
2,2000-01-05,0.467149,0.0,0.467741,0.445242,0.461821,0.0,957600
3,2000-01-06,0.473662,0.0,0.473662,0.461820,0.467149,0.0,410400
4,2000-01-07,0.463004,0.0,0.473661,0.463004,0.473661,0.0,788400
...,...,...,...,...,...,...,...,...
6281,2025-01-08,24.160000,0.0,24.270000,23.950001,24.230000,0.0,16417000
6282,2025-01-09,24.270000,0.0,24.270000,23.990000,24.160000,0.0,8286700
6283,2025-01-10,24.209999,0.0,24.440001,24.129999,24.250000,0.0,17167200
6284,2025-01-13,24.209999,0.0,24.430000,24.160000,24.209999,0.0,9941700
6285,2025-01-14,24.650000,0.0,24.670000,24.170000,24.250000,0.0,18049200

In [530]:
data.to_csv(f"{ticker}_yahoo.csv", index=False)

## DB Transfer

In [3]:
import sqlite3

# Caminhos para os bancos de dados
source_db = r"D:\Fausto Stangler\Documentos\Python\FLY\backend\data - Copy\metadados.db"
target_db = r"D:\Fausto Stangler\Documentos\Python\FLY\backend\data\app_raw.db"

# Conectando aos bancos
source_conn = sqlite3.connect(source_db)
target_conn = sqlite3.connect(target_db)

# Criando cursores
source_cursor = source_conn.cursor()
target_cursor = target_conn.cursor()

In [13]:
# Listar todas as tabelas do banco de dados de origem
source_cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = source_cursor.fetchall()

# Corrigindo a extração dos nomes das tabelas
tables = [table[0] for table in tables]  # Extraindo o primeiro elemento de cada tupla

# Remover tabelas internas do SQLite
tables = [table for table in tables if not table.startswith("sqlite_")]
print("Tabelas encontradas:", tables)

Tabelas encontradas: ['company_info', 'nsd', 'stock_data']

In [1]:
import sqlite3
import os


def copiar_tabela(db_origem, tabela_origem, db_destino, tabela_destino):
    """
    Copia uma tabela de um banco de dados SQLite para outro.
    Se o banco ou a tabela de destino não existirem, eles serão criados.

    Parâmetros:
        db_origem (str): Caminho do banco de dados de origem.
        tabela_origem (str): Nome da tabela no banco de origem.
        db_destino (str): Caminho do banco de dados de destino.
        tabela_destino (str): Nome da tabela no banco de destino.
    """

    # Criar banco de destino se não existir
    if not os.path.exists(db_destino):
        print(f"Criando banco de dados de destino: {db_destino}")
        open(db_destino, "w").close()  # Cria um arquivo vazio

    # Conectar aos bancos de dados
    origem_conn = sqlite3.connect(db_origem)
    destino_conn = sqlite3.connect(db_destino)
    destino_conn.execute("PRAGMA temp_store=MEMORY;")
    destino_conn.execute("PRAGMA locking_mode=NORMAL;")

    origem_cursor = origem_conn.cursor()
    destino_cursor = destino_conn.cursor()
    destino_cursor.execute("PRAGMA journal_mode=WAL;")
    destino_cursor.execute("PRAGMA synchronous=NORMAL;")

    try:
        # Obter a estrutura da tabela de origem
        origem_cursor.execute(f"SELECT sql FROM sqlite_master WHERE type='table' AND name='{tabela_origem}';")
        create_table_sql = origem_cursor.fetchone()

        if create_table_sql:
            # Verificar se a tabela de destino já existe
            destino_cursor.execute(f"SELECT name FROM sqlite_master WHERE type='table' AND name='{tabela_destino}';")
            table_exists = destino_cursor.fetchone()

            if table_exists:
                print(f"Removendo a tabela {tabela_destino} do banco de destino, pois já existe...")
                destino_cursor.execute(f"DROP TABLE IF EXISTS {tabela_destino};")

            # Criar a tabela no banco de destino
            create_table_sql = create_table_sql[0].replace(tabela_origem, tabela_destino)
            print(f"Criando a tabela: {tabela_destino} no banco de destino.")
            destino_cursor.execute(create_table_sql)

            # Copiar os dados da tabela de origem para a de destino
            print(f"Copiando dados da tabela {tabela_origem} para {tabela_destino}...")
            origem_cursor.execute(f"SELECT * FROM {tabela_origem};")
            rows = origem_cursor.fetchall()

            if rows:
                placeholders = ", ".join(["?"] * len(rows[0]))  # Criar placeholders para inserção
                insert_sql = f"INSERT INTO {tabela_destino} VALUES ({placeholders})"
                destino_cursor.executemany(insert_sql, rows)
                destino_conn.commit()

            print(f"Dados copiados com sucesso para {tabela_destino}")

        else:
            print(f"Erro: A tabela {tabela_origem} não foi encontrada no banco de origem.")

        destino_conn.execute("PRAGMA wal_checkpoint(FULL);")

        # Run ANALYZE to update statistics for query optimization
        destino_conn.execute("ANALYZE")

        # Run REINDEX to rebuild indexes for better performance
        destino_conn.execute("REINDEX")

        # Run VACUUM to reduce file size and defragment the database
        destino_conn.execute("VACUUM")

    except sqlite3.Error as e:
        print(f"Erro ao copiar a tabela: {e}")

    finally:
        # Fechar conexões
        origem_conn.close()
        destino_conn.close()
    return True

In [6]:
db_origem = r"D:\Fausto Stangler\Documentos\Python\FLY\backend\data - Copy\metadados.db"
# db_origem = r"D:\Fausto Stangler\Documentos\Python\FLY\backend\data - Copy\statements standart.db"
db_destino = r"D:\Fausto Stangler\Documentos\Python\FLY\backend\data\app_raw.db"


db_origem = r"D:\Fausto Stangler\Documentos\Python\FLY\backend\data - Copy\statements standart.db"
tabela_origem = "statements standart"
tabela_destino = "tbl_statements_normalized"

In [3]:
import sqlite3
import os


def renomear_coluna(db_path, tabela, coluna_atual, nova_coluna):
    """
    Renomeia uma coluna específica em uma tabela de um banco de dados SQLite.

    Parâmetros:
        db_path (str): Caminho do banco de dados SQLite.
        tabela (str): Nome da tabela onde a coluna será renomeada.
        coluna_atual (str): Nome atual da coluna.
        nova_coluna (str): Novo nome da coluna.

    Retorna:
        bool: True se a operação foi bem-sucedida, False caso contrário.
    """

    # Verificar se o banco de dados existe
    if not os.path.exists(db_path):
        print(f"Erro: O banco de dados '{db_path}' não foi encontrado.")
        return False

    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    try:
        # Obter informações sobre a tabela
        cursor.execute(f"PRAGMA table_info({tabela});")
        colunas = cursor.fetchall()

        # Verificar se a coluna atual existe na tabela
        nomes_colunas = [col[1] for col in colunas]
        if coluna_atual not in nomes_colunas:
            print(f"Erro: A coluna '{coluna_atual}' não existe na tabela '{tabela}'.")
            return False

        # Gerar um novo esquema da tabela com a coluna renomeada
        colunas_modificadas = [nova_coluna if col[1] == coluna_atual else col[1] for col in colunas]
        colunas_str = ", ".join(colunas_modificadas)

        # Criar uma nova tabela temporária com a nova estrutura
        cursor.execute(f"CREATE TABLE temp_{tabela} AS SELECT {', '.join(nomes_colunas)} FROM {tabela};")

        # Renomear a tabela original e recriar com o novo esquema
        cursor.execute(f"DROP TABLE {tabela};")
        cursor.execute(f"CREATE TABLE {tabela} ({colunas_str});")

        # Copiar os dados da tabela temporária para a nova tabela
        cursor.execute(f"INSERT INTO {tabela} SELECT * FROM temp_{tabela};")
        cursor.execute(f"DROP TABLE temp_{tabela};")

        conn.commit()
        print(f"Sucesso: A coluna '{coluna_atual}' foi renomeada para '{nova_coluna}' na tabela '{tabela}'.")
        return True

    except sqlite3.Error as e:
        print(f"Erro ao renomear a coluna: {e}")
        return False

    finally:
        conn.close()

In [5]:
db_origem = r"D:\Fausto Stangler\Documentos\Python\FLY\backend\data - Copy\statements standart.db"
db_destino = r"D:\Fausto Stangler\Documentos\Python\FLY\backend\data\app_raw.db"

tabela_origem = "statements_standart"
tabela_destino = "tbl_statements_normalized"


tabela_alvo = "tbl_nsd"
coluna_atual = "tbl_nsd"
nova_coluna = "nsd"

# copiar_tabela(db_origem, tabela_origem, db_destino, tabela_destino)

renomear_coluna(db_destino, tabela_alvo, coluna_atual, nova_coluna)

Sucesso: A coluna 'tbl_nsd' foi renomeada para 'nsd' na tabela 'tbl_nsd'.

True

### IP Change TOR

In [8]:
import requests
from stem import Signal
from stem.control import Controller

# Configurar o proxy do Tor
proxies = {"http": "socks5h://127.0.0.1:9050", "https": "socks5h://127.0.0.1:9050"}

# URL para verificar o IP público
url = "https://check.torproject.org/api/ip"


def renew_tor_ip():
    """Solicita um novo IP do Tor."""
    with Controller.from_port(port=9051) as controller:
        controller.authenticate(password="my_password")  # Defina essa senha no torrc
        controller.signal(Signal.NEWNYM)


# Primeiro IP
response1 = requests.get(url, proxies=proxies)
ip1 = response1.json()["IP"]
print(f"IP antes da mudança: {ip1}")

# Troca o IP via Tor
renew_tor_ip()

# Segundo IP (espera alguns segundos para que a rede Tor atualize)
import time

time.sleep(5)  # Tempo para Tor aplicar a nova identidade

response2 = requests.get(url, proxies=proxies)
ip2 = response2.json()["IP"]
print(f"IP depois da mudança: {ip2}")

# Verifica se o IP mudou
if ip1 != ip2:
    print("✅ IP mudou com sucesso!")
else:
    print("❌ O IP não mudou. Tente novamente.")

ConnectionError: SOCKSHTTPSConnectionPool(host='check.torproject.org', port=443): Max retries exceeded with url: /api/ip (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001D24B6CB880>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

### Proxy List

In [3]:
import requests

url = "https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=1000&country=all"
response = requests.get(url)
proxies_list = response.text.splitlines()
proxies_list

['54.38.181.125:3128',
 '43.153.113.33:13001',
 '128.199.202.122:8080',
 '47.251.54.0:6698',
 '27.189.135.200:8089',
 '134.199.157.223:30001',
 '85.10.199.48:80',
 '154.90.48.76:80',
 '49.51.195.196:13001',
 '43.153.48.134:13001',
 '49.51.204.163:13001',
 '47.254.28.155:8081',
 '222.189.81.127:8089',
 '27.189.130.181:8089',
 '43.153.36.171:13001',
 '195.114.209.50:80',
 '9.223.187.19:3128',
 '84.39.112.144:3128',
 '59.37.95.35:8072',
 '43.135.149.110:13001',
 '91.107.154.214:80',
 '138.68.60.8:80',
 '43.153.103.58:13001',
 '171.240.216.48:5105',
 '182.149.82.36:2324',
 '43.135.137.249:13001',
 '47.56.110.204:8989',
 '43.159.141.118:13001',
 '43.130.12.39:13001',
 '85.132.37.9:1313',
 '43.135.138.66:13001',
 '34.81.160.132:80',
 '43.153.48.116:13001',
 '158.255.77.169:80',
 '47.238.149.53:30007',
 '43.153.7.172:13001',
 '43.130.44.212:13001',
 '198.74.51.79:8888',
 '221.231.13.198:1080',
 '170.106.108.142:13001',
 '51.254.78.223:80',
 '49.51.197.183:13001',
 '27.189.130.244:8089',
 '218.77.183.214:5224',
 '4.145.89.88:8080',
 '94.23.9.170:80',
 '43.159.148.136:13001',
 '38.242.202.236:8080',
 '165.232.129.150:80',
 '170.106.186.103:13001',
 '114.115.132.210:9030',
 '47.56.110.204:8990',
 '43.153.36.97:13001',
 '43.135.139.25:13001',
 '43.135.181.48:13001',
 '119.3.113.150:9094',
 '189.22.234.47:80',
 '116.108.21.141:10032',
 '43.130.29.151:13001',
 '113.108.13.120:8083',
 '23.247.136.248:80',
 '46.47.197.210:3128',
 '43.135.162.60:13001',
 '43.153.16.91:13001',
 '27.189.133.160:8089',
 '43.153.21.13:13001',
 '43.130.12.5:13001',
 '43.135.165.192:13001',
 '43.130.35.14:13001',
 '43.153.79.36:13001',
 '14.181.42.33:5103',
 '20.84.109.185:80',
 '43.153.95.171:13001',
 '47.238.149.53:30001',
 '43.153.76.230:13001',
 '144.139.210.56:80',
 '170.106.114.25:13001',
 '171.41.150.216:2324',
 '43.153.18.46:13001',
 '123.30.154.171:7777',
 '72.10.160.170:9439',
 '43.135.78.162:30004',
 '189.22.234.37:80',
 '159.65.230.46:8888',
 '43.153.121.25:13001',
 '222.68.35.12:8118',
 '170.106.197.21:13001',
 '43.135.145.242:13001',
 '94.153.163.226:81',
 '43.135.136.234:13001',
 '91.107.186.37:80',
 '103.155.167.22:1111',
 '158.69.118.135:38080',
 '123.154.75.18:8085',
 '170.106.104.171:13001',
 '91.107.187.112:80',
 '4.175.200.138:8080',
 '43.153.22.138:13001',
 '170.106.192.56:13001',
 '45.140.143.77:18080',
 '122.224.124.26:12080',
 '43.153.115.164:13001',
 '43.153.92.210:13001',
 '43.153.74.136:13001',
 '121.146.56.251:3131',
 '43.135.136.212:13001',
 '97.74.87.226:80',
 '43.153.97.47:8080',
 '178.63.237.156:80',
 '170.106.199.99:13001',
 '43.153.32.146:13001',
 '43.135.139.98:13001',
 '170.106.168.100:13001',
 '218.75.224.4:3309',
 '116.108.21.141:10062',
 '43.135.144.61:13001',
 '119.3.113.152:9094',
 '191.252.204.220:8080',
 '14.181.42.33:5113',
 '135.181.154.225:80',
 '43.130.9.63:13001',
 '142.93.202.130:3128',
 '81.169.213.169:8888',
 '101.71.143.237:8092',
 '145.239.196.123:80',
 '43.153.27.172:13001',
 '43.153.33.238:13001',
 '180.127.230.87:1080',
 '135.181.164.244:8888',
 '43.153.4.121:13001',
 '128.199.202.122:3128',
 '43.159.130.175:13001',
 '170.106.75.98:13001',
 '185.46.97.75:1081',
 '37.156.46.209:8080',
 '43.135.150.45:13001',
 '219.65.73.81:80',
 '152.228.154.20:80',
 '54.37.214.253:8080',
 '162.223.90.130:80',
 '72.10.160.90:25739',
 '119.3.113.151:9094',
 '43.153.101.244:13001',
 '170.106.136.235:13001',
 '219.135.229.196:7890',
 '43.153.106.210:13001',
 '5.228.144.64:8081',
 '143.198.42.182:31280',
 '72.10.160.170:4935',
 '170.106.81.199:13001',
 '176.33.13.54:3310',
 '141.98.206.21:1453',
 '164.90.242.76:3128',
 '170.245.158.76:8080',
 '171.41.150.179:2324',
 '165.225.113.220:11211',
 '171.41.128.167:2324',
 '104.129.192.181:10797',
 '118.68.114.73:10003',
 '185.105.102.179:80',
 '79.106.231.17:8080',
 '103.159.96.95:8080',
 '15.235.132.246:8080',
 '111.132.16.97:3389',
 '27.189.135.108:8089',
 '49.87.172.125:1080',
 '114.91.25.38:1080',
 '88.42.237.102:8080',
 '111.132.16.156:3389',
 '188.247.61.234:8080',
 '222.67.13.78:2324',
 '38.240.45.111:3128',
 '178.153.241.108:8080',
 '222.68.36.181:2324',
 '94.141.99.147:3128',
 '222.68.40.126:2324',
 '222.68.37.112:1080',
 '94.249.221.93:49200',
 '196.204.83.237:1976',
 '111.72.193.66:2324',
 '14.143.130.210:80',
 '182.204.182.78:1080',
 '46.64.137.233:80',
 '111.132.16.13:3389',
 '194.150.71.0:7060',
 '190.95.132.189:999',
 '114.91.25.59:1080',
 '196.204.83.228:1976',
 '103.134.222.186:8080',
 '103.235.152.170:57413',
 '222.70.146.212:1080',
 '103.243.177.129:8080',
 '222.67.12.40:1080',
 '222.67.12.185:1080',
 '114.91.24.229:1080',
 '202.136.89.142:27503',
 '172.232.121.132:8080',
 '111.72.198.12:2324',
 '182.204.181.77:1080',
 '94.249.220.135:49200',
 '222.67.8.128:1080',
 '186.148.31.19:999',
 '222.67.8.205:1080',
 '172.235.29.87:8080',
 '209.97.163.81:8888',
 '102.213.241.70:8080',
 '182.204.180.146:1080',
 '45.86.6.137:8080',
 '103.154.25.126:8080',
 '222.70.145.9:1080',
 '222.68.38.115:1080',
 '103.126.87.112:3030',
 '182.204.179.34:1080',
 '41.65.236.47:1976',
 '222.68.42.88:1080',
 '222.68.41.137:2324',
 '81.62.179.218:5472',
 '185.105.102.189:80',
 '111.72.194.201:2324',
 '222.68.36.25:1080',
 '182.204.182.147:1080',
 '222.68.36.49:1080',
 '38.255.23.131:999',
 '103.165.157.248:8090',
 '41.40.175.222:8080']

In [10]:
import requests

# List of proxies to validate
# URL to test proxy functionality
test_url = "https://httpbin.org/ip"
timeout = 5  # Set timeout to 3 seconds

results = []

for proxy in proxies_list:
    proxies = {"http": proxy, "https": proxy}

    try:
        response = requests.get(test_url, proxies=proxies, timeout=timeout)
        if response.status_code == 200:
            status = "✅ OK"
            results.append(proxies)
        else:
            status = f"⚠️ Failed (status {response.status_code})"
    except Exception as e:
        status = f"❌ Error: {type(e).__name__}"
    r = {"Proxy": proxy, "Status": status}
    print(r)

{'Proxy': '54.38.181.125:3128', 'Status': '❌ Error: ProxyError'}
{'Proxy': '43.153.113.33:13001', 'Status': '❌ Error: ConnectionError'}
{'Proxy': '128.199.202.122:8080', 'Status': '❌ Error: ProxyError'}
{'Proxy': '47.251.54.0:6698', 'Status': '❌ Error: ProxyError'}
{'Proxy': '27.189.135.200:8089', 'Status': '✅ OK'}
{'Proxy': '134.199.157.223:30001', 'Status': '✅ OK'}
{'Proxy': '85.10.199.48:80', 'Status': '❌ Error: ReadTimeout'}
{'Proxy': '154.90.48.76:80', 'Status': '❌ Error: ProxyError'}
{'Proxy': '49.51.195.196:13001', 'Status': '✅ OK'}
{'Proxy': '43.153.48.134:13001', 'Status': '❌ Error: ConnectionError'}
{'Proxy': '49.51.204.163:13001', 'Status': '✅ OK'}
{'Proxy': '47.254.28.155:8081', 'Status': '❌ Error: ProxyError'}
{'Proxy': '222.189.81.127:8089', 'Status': '❌ Error: ProxyError'}
{'Proxy': '27.189.130.181:8089', 'Status': '❌ Error: ProxyError'}
{'Proxy': '43.153.36.171:13001', 'Status': '❌ Error: ConnectionError'}
{'Proxy': '195.114.209.50:80', 'Status': '❌ Error: ProxyError'}

KeyboardInterrupt:

In [11]:
results

[{'http': '27.189.135.200:8089', 'https': '27.189.135.200:8089'},
 {'http': '134.199.157.223:30001', 'https': '134.199.157.223:30001'},
 {'http': '49.51.195.196:13001', 'https': '49.51.195.196:13001'},
 {'http': '49.51.204.163:13001', 'https': '49.51.204.163:13001'}]

## Request Cloudflare

In [ ]:
# url = 'https://sistemaswebb3-listados.b3.com.br/listedCompaniesProxy/CompanyCall/GetInitialCompanies/eyJsYW5ndWFnZSI6InB0LWJyIiwicGFnZU51bWJlciI6MSwicGFnZVNpemUiOjIwfQ=='
url

'https://sistemaswebb3-listados.b3.com.br/listedCompaniesProxy/CompanyCall/GetIndustryClassification/eyJsYW5ndWFnZSI6InB0LWJyIn0='

In [ ]:
url = 'https://sistemaswebb3-listados.b3.com.br/listedCompaniesProxy/CompanyCall/GetIndustryClassification/eyJsYW5ndWFnZSI6InB0LWJyIn0='
industry_data = session.get(url)
dados = industry_data.json()  # ou json.loads(res2.text)
# Expandir para DataFrame
rows = []
for setor in dados:
    nome_setor = setor["sector"]
    for subsetor in setor.get("subSectors", []):
        nome_subsetor = subsetor["describle"]
        for segmento in subsetor.get("segment", []):
            rows.append({
                "Setor": nome_setor,
                "Subsetor": nome_subsetor,
                "Segmento": segmento
            })

df = pd.DataFrame(rows)

{'codeCVM': '1210',
 'issuingCompany': 'BRSR',
 'companyName': 'BCO ESTADO DO RIO GRANDE DO SUL S.A.',
 'tradingName': 'BANRISUL',
 'cnpj': '92702067000196',
 'marketIndicator': '16',
 'typeBDR': '',
 'dateListing': '26/06/1972',
 'status': 'A',
 'segment': 'Bancos',
 'segmentEng': 'Banks',
 'type': '1',
 'market': 'N1'}

In [241]:
payload = {
  "codeCVM": dados['codeCVM'],
  "language": "pt-br"
}
payload = base64_payload(payload)
url_dados = f"https://sistemaswebb3-listados.b3.com.br/listedCompaniesProxy/CompanyCall/GetDetail/{payload}"

In [242]:
res3 = session.get(url_dados)

In [243]:
details = res3.json()
details

{'issuingCompany': 'BRSR',
 'companyName': 'BCO ESTADO DO RIO GRANDE DO SUL S.A.',
 'tradingName': 'BANRISUL',
 'cnpj': '92702067000196',
 'industryClassification': 'Financeiro / Intermediários Financeiros / Bancos',
 'industryClassificationEng': None,
 'activity': 'Banco Múltiplo atuante nas carteiras comercial. crédito. financiamento e investimento. crédito imobiliário. desenvolvimento e arrendamento mercantil e de investimentos.',
 'website': 'www.banrisul.com.br/ri',
 'hasQuotation': None,
 'status': 'A',
 'marketIndicator': '16',
 'market': 'BOVESPA NIVEL 1',
 'institutionCommon': 'BANRISUL',
 'institutionPreferred': 'BANRISUL',
 'code': 'BRSR5',
 'codeCVM': '1210',
 'lastDate': '17/04/2025 23:15:38',
 'otherCodes': [{'code': 'BRSR3', 'isin': 'BRBRSRACNOR3'},
  {'code': 'BRSR5', 'isin': 'BRBRSRACNPA6'},
  {'code': 'BRSR6', 'isin': 'BRBRSRACNPB4'}],
 'hasEmissions': False,
 'hasBDR': False,
 'typeBDR': None,
 'describleCategoryBVMF': None,
 'dateQuotation': '16/09/1931'}

In [244]:
url_stock_composition = f'https://sistemaswebb3-listados.b3.com.br/listedCompaniesProxy/CompanyCall/GetListedFinancial/{payload}'
res4 = session.get(url_stock_composition)
stock = res4.json()
stock.keys()
stock

{'titleInitial': 'Dados Econômico-Financeiros - R$ - mil',
 'consolidated': [{'title': 'Balanço Patrimonial  - Consolidado',
   'dateInicial': '31/12/2024',
   'dateFinal': '31/12/2023',
   'results': [{'describle': 'Ativo Imobilizado, Investimentos e Intangível',
     'value': '1.400.129',
     'value2': '1.460.834'},
    {'describle': 'Ativo Total',
     'value': '147.936.515',
     'value2': '125.667.007'}]},
  {'title': 'Demonstração do Resultado - Consolidado',
   'dateInicial': '01/01/2024 a 31/12/2024',
   'dateFinal': '01/01/2023 a 31/12/2023',
   'results': [{'describle': 'Receita da Intermediação Financeira',
     'value': '16.420.211',
     'value2': '14.479.371'},
    {'describle': 'Resultado Bruto da Intermediação Financeira',
     'value': '5.526.323',
     'value2': '4.620.492'},
    {'describle': 'Resultado de Equivalência Patrimonial',
     'value': '(1.447.769)',
     'value2': '(1.125.311)'}]},
  {'title': 'Demonstração do Fluxo de Caixa - Consolidado',
   'dateInicial': '01/01/2024 a 31/12/2024',
   'dateFinal': '01/01/2023 a 31/12/2023',
   'results': [{'describle': 'Atividades Operacionais',
     'value': '16.524.439',
     'value2': '6.055.393'},
    {'describle': 'Atividades de Investimento',
     'value': '(19.886.476)',
     'value2': '(3.346.778)'},
    {'describle': 'Atividades de Financiamento',
     'value': '(511.205)',
     'value2': '(469.215)'},
    {'describle': 'Variação Cambial sobre Caixa e Equivalentes',
     'value': '0',
     'value2': '0'},
    {'describle': 'Aumento (Redução) de Caixa e Equivalentes',
     'value': '(3.873.242)',
     'value2': '2.239.400'}]}],
 'unconsolidated': [{'title': 'Balanço Patrimonial  - Não-Consolidado',
   'dateInicial': '31/12/2024',
   'dateFinal': '31/12/2023',
   'results': [{'describle': 'Ativo Total',
     'value': '146.946.990',
     'value2': '124.340.883'},
    {'describle': 'Patrimônio Líquido',
     'value': '10.410.002',
     'value2': '9.662.088'}]},
  {'title': 'Demonstração do Resultado - Não-Consolidado',
   'dateInicial': '01/01/2024 a 31/12/2024',
   'dateFinal': '01/01/2023 a 31/12/2023',
   'results': [{'describle': 'Receita da Intermediação Financeira',
     'value': '17.216.802',
     'value2': '15.701.728'},
    {'describle': 'Resultado Bruto da Intermediação Financeira',
     'value': '6.157.258',
     'value2': '5.242.217'},
    {'describle': 'Lucro (Prejuízo) do Período',
     'value': '915.576',
     'value2': '870.104'}]},
  {'title': 'Demonstração do Fluxo de Caixa - Não-Consolidado',
   'dateInicial': '01/01/2024 a 31/12/2024',
   'dateFinal': '01/01/2023 a 31/12/2023',
   'results': [{'describle': 'Atividades Operacionais',
     'value': '16.095.347',
     'value2': '5.489.810'},
    {'describle': 'Atividades de Investimento',
     'value': '(19.499.901)',
     'value2': '(2.788.672)'},
    {'describle': 'Atividades de Financiamento',
     'value': '(508.108)',
     'value2': '(469.784)'},
    {'describle': 'Variação Cambial sobre Caixa e Equivalentes',
     'value': '0',
     'value2': '0'},
    {'describle': 'Aumento (Redução) de Caixa e Equivalentes',
     'value': '(3.912.662)',
     'value2': '2.231.354'}]}],
 'freeFloatResult': {'title': '25/04/2024',
  'describle': 'Tipos de Investidores / Ações',
  'quantity': 'Quantidade',
  'perc': 'Percentual',
  'results': [{'describle': 'Pessoas Físicas',
    'value': '145.440',
    'value2': '-'},
   {'describle': 'Pessoas Jurídicas', 'value': '4.702', 'value2': '-'},
   {'describle': 'Investidores Institucionais', 'value': '585', 'value2': '-'},
   {'describle': 'Quantidade de Ações Ordinárias',
    'value': '3.829.176',
    'value2': '1,87'},
   {'describle': 'Quantidade de Ações Preferenciais',
    'value': '203.158.041',
    'value2': '99,63'},
   {'describle': 'Total de Ações',
    'value': '206.987.217',
    'value2': '50,61'}]},
 'positionShareholders': {'informationReceived': '27/02/2025',
  'name': 'Nome',
  'on': '%ON',
  'pn': '%PN',
  'total': '%Total',
  'results': [{'describle': 'Governo do Estado do Rio Grande do Sul',
    'on': '98,13',
    'pn': '0,37',
    'total': '49,39'},
   {'describle': 'OUTROS', 'on': '1,87', 'pn': '99,63', 'total': '50,61'},
   {'describle': 'AÇÕES TESOURARIA',
    'on': '0,00',
    'pn': '0,00',
    'total': '0,00'},
   {'describle': 'TOTAL', 'on': '100,00', 'pn': '100,00', 'total': '100,00'}]},
 'outstandingShares': None,
 'capitalStockComposition': {'title': '25/04/2024',
  'results': [{'describle': 'Ordinárias', 'value': '205.064.841'},
   {'describle': 'Preferenciais', 'value': '203.909.636'},
   {'describle': 'Total', 'value': '408.974.477'}]}}

In [248]:
url = 'https://sistemaswebb3-listados.b3.com.br/listedCompaniesProxy/CompanyCall/GetInitialCompanies/eyJsYW5ndWFnZSI6InB0LWJyIiwicGFnZU51bWJlciI6MSwicGFnZVNpemUiOjIwfQ=='

payload = base64_decode(url)
payload

{'language': 'pt-br', 'pageNumber': 1, 'pageSize': 20}

In [256]:
payload = {
  "language": "pt-br",
  "pageNumber": 2,
  "pageSize": 120
}
payload = base64_payload(payload)
url_search = f'https://sistemaswebb3-listados.b3.com.br/listedCompaniesProxy/CompanyCall/GetInitialCompanies/{payload}'

res_companies = session.get(url_search)
companies = res_companies.json()
companies

{'page': {'pageNumber': 2,
  'pageSize': 120,
  'totalRecords': 2965,
  'totalPages': 25},
 'results': [{'codeCVM': '900256',
   'issuingCompany': 'AERS',
   'companyName': 'ALTO ENERGIA RENOVÁVEL S.A',
   'tradingName': 'ALTO ENERGIA',
   'cnpj': '46614985000146',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '900266',
   'issuingCompany': 'ALUB',
   'companyName': 'ALUBAM PARTICIPACOES S/A',
   'tradingName': 'ALUBAM',
   'cnpj': '14327122000100',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '917461',
   'issuingCompany': 'ALMC',
   'companyName': 'ALUBAR METAIS E CABOS S.A.',
   'tradingName': 'ALUBARMETAIS',
   'cnpj': '8262121000113',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '521019',
   'issuingCompany': 'ALMZ',
   'companyName': 'ALUMAZON COMPONENTES DA AMAZONIA S.A.',
   'tradingName': 'ALUMAZON',
   'cnpj': '4955456000166',
   'marketIndicator': '7',
   'typeBDR': '',
   'dateListing': '02/12/2019',
   'status': 'A',
   'segment': 'Carga Inicial',
   'segmentEng': 'Carga inicial',
   'type': '6',
   'market': 'MB'},
  {'codeCVM': '21490',
   'issuingCompany': 'ALUP',
   'companyName': 'ALUPAR INVESTIMENTO S/A',
   'tradingName': 'ALUPAR',
   'cnpj': '8364948000138',
   'marketIndicator': '17',
   'typeBDR': '',
   'dateListing': '02/04/2013',
   'status': 'A',
   'segment': 'Energia Elétrica',
   'segmentEng': 'Electric Utilities',
   'type': '1',
   'market': 'N2'},
  {'codeCVM': '900274',
   'issuingCompany': 'ALUS',
   'companyName': 'ALUSA ENGENHARIA S.A.',
   'tradingName': 'ALUSAENG',
   'cnpj': '58580465000149',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '910398',
   'issuingCompany': 'CBLT',
   'companyName': 'ALVOAR LACTEOS NORDESTE S/A',
   'tradingName': 'ALVOAR LACT',
   'cnpj': '10483444000189',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '900282',
   'issuingCompany': 'AMPS',
   'companyName': 'AMAM PARTICIPACOES SPE S.A.',
   'tradingName': 'AMAM',
   'cnpj': '19165656000192',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '900035',
   'issuingCompany': 'AATA',
   'companyName': 'AMATA  S.A.',
   'tradingName': 'AMATA',
   'cnpj': '7909776000178',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '913301',
   'issuingCompany': 'AMTG',
   'companyName': 'AMAZONAS GERAÇÃO E TRANSMISSÃO DE ENERGIA S.A.',
   'tradingName': 'AM GER TRANS',
   'cnpj': '17957780000165',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '916862',
   'issuingCompany': 'AMSC',
   'companyName': 'AMAZONIA SOLAR SEC. DE CREDITOS FINANCEIROS',
   'tradingName': 'AMAZONIA SOL',
   'cnpj': '43102521000162',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '912170',
   'issuingCompany': 'AMBA',
   'companyName': 'AMBAR ENERGIA LTDA',
   'tradingName': 'AMBARENERGIA',
   'cnpj': '1645009000384',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '915983',
   'issuingCompany': 'ARUG',
   'companyName': 'Ambar Uruguaiana Energia S.A.',
   'tradingName': 'AMBARURUGUAI',
   'cnpj': '1600202000137',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '23264',
   'issuingCompany': 'ABEV',
   'companyName': 'AMBEV S.A.',
   'tradingName': 'AMBEV S/A',
   'cnpj': '7526557000100',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/10/2013',
   'status': 'A',
   'segment': 'Cervejas e Refrigerantes',
   'segmentEng': 'Beer and Soft Drinks',
   'type': '1',
   'market': ''},
  {'codeCVM': '900040',
   'issuingCompany': 'AMTL',
   'companyName': 'AMBIENTAL LIMPEZA URBANA E SANEAMENTO LTDA',
   'tradingName': 'AMB LIMPEZA',
   'cnpj': '3094629000136',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '900364',
   'issuingCompany': 'AMTR',
   'companyName': 'AMBIENTAL METROSUL CONCESSIONARIA DE SANEAMENTO SP',
   'tradingName': 'AMB METROSUL',
   'cnpj': '36641320000178',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '914663',
   'issuingCompany': 'AMMS',
   'companyName': 'AMBIENTAL MS PANTANAL SPE S.A',
   'tradingName': 'AMBIENTAL MS',
   'cnpj': '40074069000184',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '916338',
   'issuingCompany': 'ABPA',
   'companyName': 'AMBIENTAL PARTICIPACOES S.A.',
   'tradingName': 'AMBIENTALPAR',
   'cnpj': '38138329000196',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '22/12/2021',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '24961',
   'issuingCompany': 'AMBP',
   'companyName': 'AMBIPAR PARTICIPACOES E EMPREENDIMENTOS S/A',
   'tradingName': 'AMBIPAR',
   'cnpj': '12648266000124',
   'marketIndicator': '18',
   'typeBDR': '',
   'dateListing': '02/07/2020',
   'status': 'A',
   'segment': 'Água e Saneamento',
   'segmentEng': 'Water Utilities',
   'type': '1',
   'market': 'NM'},
  {'codeCVM': '914077',
   'issuingCompany': 'ANET',
   'companyName': 'AMERICA NET S.A.',
   'tradingName': 'AMERICA NET',
   'cnpj': '1778972000174',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '917658',
   'issuingCompany': 'ATBR',
   'companyName': 'AMERICAN TOWER DO BRASIL - CESSAO DE INFRAESTRUTUR',
   'tradingName': 'AMER TOWER',
   'cnpj': '4052108000189',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '20990',
   'issuingCompany': 'AMER',
   'companyName': 'AMERICANAS S.A',
   'tradingName': 'AMERICANAS',
   'cnpj': '776574000156',
   'marketIndicator': '18',
   'typeBDR': '',
   'dateListing': '26/07/2007',
   'status': 'A',
   'segment': 'Produtos Diversos',
   'segmentEng': 'Diversified Retailers',
   'type': '1',
   'market': 'NM'},
  {'codeCVM': '3050',
   'issuingCompany': 'CBEE',
   'companyName': 'AMPLA ENERGIA E SERVICOS S.A.',
   'tradingName': 'AMPLA ENERG',
   'cnpj': '33050071000158',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '06/03/1969',
   'status': 'A',
   'segment': 'Energia Elétrica',
   'segmentEng': 'Electric Utilities',
   'type': '1',
   'market': ''},
  {'codeCVM': '914051',
   'issuingCompany': 'ANDA',
   'companyName': 'ANDALI AS',
   'tradingName': 'ANDALIAS',
   'cnpj': '2227264000108',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '900316',
   'issuingCompany': 'ANDH',
   'companyName': 'ANDORINHA ENERGIAS RENOVAVEIS S/A',
   'tradingName': 'ANDORINHA',
   'cnpj': '17613512000126',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '912535',
   'issuingCompany': 'CANT',
   'companyName': 'ANDRADE GUTIERREZ PARTICIPACOES S.A.',
   'tradingName': 'AGPART',
   'cnpj': '4031960000170',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '29/10/2001',
   'status': 'A',
   'segment': 'Holdings Diversificadas',
   'segmentEng': 'Holdings - Diversified',
   'type': '7',
   'market': ''},
  {'codeCVM': '900191',
   'issuingCompany': 'AGUT',
   'companyName': 'ANDRADE GUTIERREZ S/A',
   'tradingName': 'AGUTIERREZ',
   'cnpj': '17262197000130',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '26832',
   'issuingCompany': 'ANEM',
   'companyName': 'ANEMUS WIND HOLDING S.A.',
   'tradingName': 'ANEMUS WIND',
   'cnpj': '38482780000126',
   'marketIndicator': '8',
   'typeBDR': '',
   'dateListing': '08/06/2022',
   'status': 'A',
   'segment': 'Energia Elétrica',
   'segmentEng': 'Electric Utilities',
   'type': '1',
   'market': ''},
  {'codeCVM': '917517',
   'issuingCompany': 'AGEM',
   'companyName': 'ANGULO45 EMPREENDIMENTOS S.A',
   'tradingName': 'ANGULO45 EMP',
   'cnpj': '39435090000189',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '900288',
   'issuingCompany': 'AEDU',
   'companyName': 'ANHANGUERA EDUCACIONAL PARTICIPACOES S.A',
   'tradingName': 'ANHANGUERA',
   'cnpj': '4310392000146',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '23248',
   'issuingCompany': 'ANIM',
   'companyName': 'ANIMA HOLDING S.A.',
   'tradingName': 'ANIMA',
   'cnpj': '9288252000132',
   'marketIndicator': '18',
   'typeBDR': '',
   'dateListing': '24/10/2013',
   'status': 'A',
   'segment': 'Serviços Educacionais',
   'segmentEng': 'Education Services',
   'type': '1',
   'market': 'NM'},
  {'codeCVM': '917522',
   'issuingCompany': 'AOVS',
   'companyName': 'AOVS SISTEMAS DE INFORMÁTICA S.A.',
   'tradingName': 'AOVSSISTEMA',
   'cnpj': '5555382000133',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '909697',
   'issuingCompany': 'ACES',
   'companyName': 'APERAM INOX AMERICA DO SUL S.A.',
   'tradingName': 'APERAM',
   'cnpj': '33390170000189',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Siderurgia',
   'segmentEng': 'Steel',
   'type': '7',
   'market': ''},
  {'codeCVM': '914531',
   'issuingCompany': 'APOL',
   'companyName': 'APOLLO 17 PARTICIPACOES S.A',
   'tradingName': 'APOLLO 17',
   'cnpj': '37606330000135',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '914325',
   'issuingCompany': 'ASPF',
   'companyName': 'APSEN FARMACEUTICA S.A.',
   'tradingName': 'APSEN FARMA',
   'cnpj': '62462015000129',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '917507',
   'issuingCompany': 'AFOZ',
   'companyName': 'AQUA-FOZ AQUÁRIO DE FOZ DO IGUAÇU S.A.',
   'tradingName': 'AQUAFOZAQU',
   'cnpj': '42651953000160',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '900027',
   'issuingCompany': 'AARJ',
   'companyName': 'AQUA-RIO AQUARIO MARINHO DO RIO DE JANEIRO S/A',
   'tradingName': 'AQUARIO',
   'cnpj': '19624745000150',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '900357',
   'issuingCompany': 'ARSN',
   'companyName': 'ARAUCARIA SANEAMENTO S/A',
   'tradingName': 'ARAUCARIA',
   'cnpj': '12049167000126',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '915967',
   'issuingCompany': 'INSU',
   'companyName': 'Arco Insuretech S.A.',
   'tradingName': 'ARCOINSURETE',
   'cnpj': '43751004000114',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '912063',
   'issuingCompany': 'ARSP',
   'companyName': 'ARCOS SANEAMENTO E PARTICIPACOES LTDA',
   'tradingName': 'ARCOS SANEAM',
   'cnpj': '29291541000106',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '910448',
   'issuingCompany': 'ARCV',
   'companyName': 'ARCOVERDE TRANSMISSÃO DE ENERGIA S.A.',
   'tradingName': 'ARCOVERDE',
   'cnpj': '28008887000183',
   'marketIndicator': '1',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '911883',
   'issuingCompany': 'AREG',
   'companyName': 'AREIA ENERGIA S/A',
   'tradingName': 'AREIAENERGIA',
   'cnpj': '7321320000192',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '914473',
   'issuingCompany': 'ARPR',
   'companyName': 'ARES 2 PARTICIPAÇÕES S.A.',
   'tradingName': 'ARES 2 PARTI',
   'cnpj': '27317154000168',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '914085',
   'issuingCompany': 'ARON',
   'companyName': 'ARES ONE PARTICIPACOES S.A.',
   'tradingName': 'ARES ONE PAR',
   'cnpj': '38350319000110',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '917580',
   'issuingCompany': 'AGBP',
   'companyName': 'ARGEB ENERGIA EMPREENDIMENTOS E PARTICIPACOES S.A.',
   'tradingName': 'ARGEB',
   'cnpj': '47680198000165',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '24120',
   'issuingCompany': 'AEEP',
   'companyName': 'ARGO ENERGIA EMPREENDIMENTOS E PARTICIPAÇÕES S.A.',
   'tradingName': 'ARGO ENERGIA',
   'cnpj': '24624551000194',
   'marketIndicator': '8',
   'typeBDR': '',
   'dateListing': '17/03/2023',
   'status': 'A',
   'segment': 'Não Classificado',
   'segmentEng': 'E',
   'type': '1',
   'market': ''},
  {'codeCVM': '24210',
   'issuingCompany': 'TRGO',
   'companyName': 'ARGO TRANSMISSAO DE ENERGIA S.A.',
   'tradingName': 'ARGOTRANSM',
   'cnpj': '24624490000165',
   'marketIndicator': '8',
   'typeBDR': '',
   'dateListing': '01/03/2023',
   'status': 'A',
   'segment': 'Não Classificado',
   'segmentEng': 'E',
   'type': '1',
   'market': ''},
  {'codeCVM': '26662',
   'issuingCompany': 'ARGV',
   'companyName': 'ARGO V TRANSMISSAO DE ENERGIA SA',
   'tradingName': 'ARGOVTRANS',
   'cnpj': '20514590000188',
   'marketIndicator': '8',
   'typeBDR': '',
   'dateListing': '08/10/2024',
   'status': 'A',
   'segment': 'Energia Elétrica',
   'segmentEng': 'Electric Utilities',
   'type': '1',
   'market': ''},
  {'codeCVM': '26670',
   'issuingCompany': 'SPRZ',
   'companyName': 'ARGO VI TRASMISSAO DE ENERGIA SA',
   'tradingName': 'ARGOVITRANS',
   'cnpj': '20514555000169',
   'marketIndicator': '8',
   'typeBDR': '',
   'dateListing': '08/10/2024',
   'status': 'A',
   'segment': 'Energia Elétrica',
   'segmentEng': 'Electric Utilities',
   'type': '1',
   'market': ''},
  {'codeCVM': '26654',
   'issuingCompany': 'TJMM',
   'companyName': 'ARGO VII TRANSMISSÃO DE ENERGIA S.A.',
   'tradingName': 'ARGOTRANSVII',
   'cnpj': '21728083000100',
   'marketIndicator': '8',
   'typeBDR': '',
   'dateListing': '08/10/2024',
   'status': 'A',
   'segment': 'Energia Elétrica',
   'segmentEng': 'Electric Utilities',
   'type': '1',
   'market': ''},
  {'codeCVM': '917654',
   'issuingCompany': 'ARKL',
   'companyName': 'ARKLOK \x96 EQUIPAMENTOS DE INFORMÁTICA S.A',
   'tradingName': 'ARKLOK',
   'cnpj': '10489713000114',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '26069',
   'issuingCompany': 'ARML',
   'companyName': 'ARMAC LOCAÇÃO. LOGÍSTICA E SERVIÇOS S.A.',
   'tradingName': 'ARMAC',
   'cnpj': '242184000104',
   'marketIndicator': '18',
   'typeBDR': '',
   'dateListing': '26/07/2021',
   'status': 'A',
   'segment': 'Máq. e Equip. Industriais',
   'segmentEng': 'Machines and Industrial Equipments',
   'type': '1',
   'market': 'NM'},
  {'codeCVM': '900308',
   'issuingCompany': 'AMTE',
   'companyName': 'ARMAZEM MATEUS S.A.',
   'tradingName': 'ARMAZEMMATEU',
   'cnpj': '23439441001323',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '900332',
   'issuingCompany': 'ARMB',
   'companyName': 'ARMCO DO BRASIL S.A.',
   'tradingName': 'ARMCO',
   'cnpj': '71586952000187',
   'marketIndicator': '99',
   'typeBDR': '',
   'dateListing': '31/12/9999',
   'status': 'A',
   'segment': 'Não Classificados',
   'segmentEng': 'Not Classified',
   'type': '7',
   'market': ''},
  {'codeCVM': '900340',
   'issuingCompany': 'ARQU',
   'companyName': 'ARTECOLA QUIMICA S.A.',
   'tradingName': 'ARTECOLA',
   'cnpj': '44699346000103',

### Start

In [273]:
import requests
import json
import base64
from urllib.parse import quote
import pandas as pd

In [274]:
def base64_decode(token_base64: str) -> dict:
    """
    Decodifica um payload Base64 da B3 e retorna como dicionário JSON.

    Args:
        token_base64 (str): Token codificado (ex: 'eyJsYW5ndWFnZSI6InB0LWJyIn0=')

    Returns:
        dict: Dicionário com os dados decodificados
    """
    if token_base64.startswith("https"):
        token_base64 = token_base64.rstrip("/").split("/")[-1]

    try:
        decoded_bytes = base64.b64decode(token_base64)
        decoded_str = decoded_bytes.decode()
        return json.loads(decoded_str)
    except Exception as e:
        print(f"[ERRO] Falha ao decodificar: {e}")
        return {}

def base64_payload(payload: dict) -> str:
    """
    Gera um token Base64 com os parâmetros corretos para o endpoint da B3.

    Args:
        payload (dict): Dicionário com parâmetros como language, pageNumber, etc.

    Returns:
        str: String Base64 pronta para ser usada na URL.
    """
    json_str = json.dumps(payload, separators=(',', ':'))
    base64_encoded = base64.b64encode(json_str.encode()).decode()
    return base64_encoded

In [275]:
# Passo 1: Criar uma sessão
session = requests.Session()

# Headers de navegador
headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "pt-BR,pt;q=0.9",
}
# Passo 2: Fazer a primeira requisição (gera os cookies)
url_start = "https://sistemaswebb3-listados.b3.com.br/listedCompaniesPage/?language=pt-br"
response_start = session.get(url_start, headers=headers)

In [276]:
companies['page']['totalPages']

25

In [278]:
all_results = []
for i in range(1, companies['page']['totalPages'] + 1):
  payload = {
  "language": "pt-br",
  "pageNumber": i,
  "pageSize": 120
  }
  payload = base64_payload(payload)
  url_search = f'https://sistemaswebb3-listados.b3.com.br/listedCompaniesProxy/CompanyCall/GetInitialCompanies/{payload}'

  res_companies = session.get(url_search)
  companies = res_companies.json()
  results = companies['results']
  all_results.extend(results)
df_empresas = pd.DataFrame(all_results)
issuing_company_list = df_empresas['issuingCompany'].dropna().unique().tolist()

In [279]:
def get_company_dados(payload):
    payload = base64_payload(payload)
    url_dados = f"https://sistemaswebb3-listados.b3.com.br/listedCompaniesProxy/CompanyCall/GetInitialCompanies/{payload}"

    res2 = session.get(url_dados)
    dados = res2.json()  # ou json.loads(res2.text)
    empresas = dados.get("results", [])

    # Filtrar apenas a empresa com código exato "LREN"
    dados = [e for e in empresas if e.get("issuingCompany") == issuingCompany][0]
    return dados

In [284]:
all_dados = []
for issuingCompany in issuing_company_list:
    print(issuingCompany)
    payload = {
        "language": 'pt-br',
        "pageNumber": 1,
        "pageSize": 20,
        "company": issuingCompany
    }
    dados = get_company_dados(payload)
    all_dados.extend(dados)

UQMU
2WAV
ENEY
PTGU
TZRD
QVQP
NNPY
GRDR
BODY
AACL
AYOS
AMCT
ATBC
ABAP
ABPR
ABCC

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [285]:
payload

{'language': 'pt-br', 'pageNumber': 1, 'pageSize': 20, 'company': 'ABCC'}

In [287]:
payload = base64_payload(payload)
url_dados = f"https://sistemaswebb3-listados.b3.com.br/listedCompaniesProxy/CompanyCall/GetInitialCompanies/{payload}"
url_dados

'https://sistemaswebb3-listados.b3.com.br/listedCompaniesProxy/CompanyCall/GetInitialCompanies/ImV5SnNZVzVuZFdGblpTSTZJbkIwTFdKeUlpd2ljR0ZuWlU1MWJXSmxjaUk2TVN3aWNHRm5aVk5wZW1VaU9qSXdMQ0pqYjIxd1lXNTVJam9pUVVKRFF5Sjki'